import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { motion } from "framer-motion";
import VehicleSelector from "../components/VehicleSelector";
const parkingTypes = [
    { type: "paralelo", num: "01", label: "Paralelo", description: "Entre dos autos en fila" },
    { type: "bateria", num: "02", label: "Batería", description: "Perpendicular al bordillo" },
    { type: "diagonal", num: "03", label: "Diagonal", description: "En ángulo en el cajón" },
    { type: "pendiente", num: "04", label: "En Pendiente", description: "Cuesta arriba o abajo" },
];
export default function ParkingHubPage() {
    return (_jsxs("div", { className: "px-5 pt-14 pb-4 max-w-lg mx-auto", children: [_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.3 }, children: _jsxs(Link, { to: "/", className: "inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground transition-colors mb-10 tracking-wide uppercase", children: [_jsx(ArrowLeft, { size: 14 }), "Inicio"] }) }), _jsxs(motion.div, { className: "mb-8", initial: { opacity: 0, y: -16 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.4, delay: 0.05, ease: "easeOut" }, children: [_jsx("h1", { className: "text-7xl leading-none text-foreground", style: { fontFamily: "'Bebas Neue', cursive", letterSpacing: "0.03em" }, children: "Estacionar" }), _jsxs("div", { className: "flex items-center gap-3 mt-3", children: [_jsx("div", { className: "w-6 h-px bg-primary" }), _jsx("p", { className: "text-muted-foreground text-sm font-light tracking-widest uppercase", children: "Elige el tipo de estacionamiento" })] })] }), _jsxs(motion.div, { className: "mb-8", initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.35, delay: 0.12, ease: "easeOut" }, children: [_jsx("p", { className: "text-[10px] text-muted-foreground/60 tracking-widest uppercase mb-2", children: "Mi veh\u00EDculo" }), _jsx(VehicleSelector, {})] }), _jsx("div", { className: "flex flex-col", children: parkingTypes.map(({ type, num, label, description }, i) => (_jsx(motion.div, { initial: { opacity: 0, x: -16 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.35, delay: 0.18 + i * 0.08, ease: "easeOut" }, children: _jsxs(Link, { to: `/parking/${type}`, className: "group flex items-center gap-4 py-4 border-b border-border/50 transition-all duration-200 active:scale-[0.98]", children: [_jsx("span", { className: "text-4xl w-10 shrink-0 text-primary/30 group-hover:text-primary/60 transition-colors duration-200 leading-none", style: { fontFamily: "'Bebas Neue', cursive" }, children: num }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h2", { className: "font-medium text-sm text-foreground", children: label }), _jsx("p", { className: "text-xs text-muted-foreground mt-0.5", children: description })] }), _jsx(ArrowRight, { size: 15, className: "text-muted-foreground/30 group-hover:text-primary group-hover:translate-x-0.5 transition-all duration-200 shrink-0" })] }) }, type))) })] }));
}
